### ISSUE TITLE
Exception on Windows when running gvm available or gvm install

### ISSUE THREAD

**Issue by stefanjarina** [andrewkroh/gvm#27]
Hello,

I am getting this strange error when trying to install new version of go:

OS: Windows
shell: Powerhell 7.0.3 (same issue in powershell 5.1)

```ps
> gvm install 1.15.3
Installing go-1.15.3. Please wait...
DEBU[0000] downloading file                              package=common url="https://storage.googleapis.com/golang/go1.15.3.windows-amd64.zip"
Exception 0xc0000005 0x0 0x7fffcd632fff 0x14f0000
PC=0x14f0000

syscall.Syscall6(0x7fffcc645b20, 0x4, 0xc04200a330, 0x0, 0xc04215ff88, 0xc04215fe80, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/syscall_windows.go:184 +0xfc
syscall.GetAddrInfoW(0xc04200a330, 0x0, 0xc04215ff88, 0xc04215fe80, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/syscall/zsyscall_windows.go:1717 +0xc1
net.(*Resolver).lookupIP.func1(0xc042050c20, 0x16, 0xc0420423c0)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/lookup_windows.go:96 +0x106
created by net.(*Resolver).lookupIP
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/lookup_windows.go:87 +0x93

goroutine 1 [select]:
net/http.(*Transport).getConn(0xa0e080, 0xc042144360, 0x0, 0xc04207c6c0, 0x5, 0xc042050c20, 0x1a, 0x0, 0x0, 0xc0420712e8)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/http/transport.go:962 +0x55f
net/http.(*Transport).RoundTrip(0xa0e080, 0xc04215a100, 0xa0e080, 0xbfdfd069dbc76d64, 0x29ecf2e599)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/http/transport.go:409 +0x639
net/http.send(0xc04215a000, 0x8340e0, 0xa0e080, 0xbfdfd069dbc76d64, 0x29ecf2e599, 0xa13b20, 0xc042074250, 0xbfdfd069dbc76d64, 0xc0420715e0, 0x1)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/http/client.go:252 +0x18c
net/http.(*Client).send(0xc0421441b0, 0xc04215a000, 0xbfdfd069dbc76d64, 0x29ecf2e599, 0xa13b20, 0xc042074250, 0x0, 0x1, 0x4106cf)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/http/client.go:176 +0x101
net/http.(*Client).Do(0xc0421441b0, 0xc04215a000, 0xc04207c6c0, 0x40, 0x0)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/http/client.go:615 +0x294
net/http.(*Client).Get(0xc0421441b0, 0xc04207c6c0, 0x40, 0xc042158000, 0xaa, 0x6)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/http/client.go:396 +0xa4
github.com/andrewkroh/gvm/common.downloadFile(0xc04207c6c0, 0x40, 0xc042066140, 0x41, 0x0, 0x0, 0x0, 0x0, 0xa08600)
        /home/travis/gopath/src/github.com/andrewkroh/gvm/common/common.go:36 +0xbe
github.com/andrewkroh/gvm/common.DownloadFile(0xc04207c6c0, 0x40, 0xc042066140, 0x41, 0x5, 0xc04207c6c0, 0x40, 0x0)
        /home/travis/gopath/src/github.com/andrewkroh/gvm/common/common.go:22 +0x23c
github.com/andrewkroh/gvm.(*Manager).installBinary(0xc042122090, 0xc0420eace0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/andrewkroh/gvm/binrepo.go:35 +0x299
github.com/andrewkroh/gvm.(*Manager).Install(0xc042122090, 0xc0420eace0, 0xc042071c58, 0x1, 0x1, 0x25)
        /home/travis/gopath/src/github.com/andrewkroh/gvm/gvm.go:213 +0x11b
main.installCommand.func1(0xc042122090, 0x0, 0x0)
        /home/travis/gopath/src/github.com/andrewkroh/gvm/cmd/gvm/install.go:40 +0x3e6
main.main()
        /home/travis/gopath/src/github.com/andrewkroh/gvm/cmd/gvm/gvm.go:100 +0xe7a

goroutine 19 [select]:
net/http.setRequestCancel.func3(0x0, 0xc0421442a0, 0xc04209a730, 0xc042052e0c, 0xc042044180)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/http/client.go:323 +0x101
created by net/http.setRequestCancel
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/http/client.go:322 +0x2b3

goroutine 20 [select]:
net.(*Resolver).LookupIPAddr(0xa12a70, 0x8377a0, 0xc042042240, 0xc042050c20, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/lookup.go:212 +0x514
net.(*Resolver).internetAddrList(0xa12a70, 0x8377a0, 0xc042042240, 0x7ec3ca, 0x3, 0xc042050c20, 0x1a, 0x0, 0x0, 0x0, ...)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/ipsock.go:293 +0x5cb
net.(*Resolver).resolveAddrList(0xa12a70, 0x8377a0, 0xc042042240, 0x7ec749, 0x4, 0x7ec3ca, 0x3, 0xc042050c20, 0x1a, 0x0, ...)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/dial.go:193 +0x513
net.(*Dialer).DialContext(0xc042100060, 0x837760, 0xc042052098, 0x7ec3ca, 0x3, 0xc042050c20, 0x1a, 0x0, 0x0, 0x0, ...)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/dial.go:375 +0x232
net.(*Dialer).DialContext-fm(0x837760, 0xc042052098, 0x7ec3ca, 0x3, 0xc042050c20, 0x1a, 0x402edd, 0x6121a0, 0xc042052098, 0x784200)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/http/transport.go:46 +0x7a
net/http.(*Transport).dial(0xa0e080, 0x837760, 0xc042052098, 0x7ec3ca, 0x3, 0xc042050c20, 0x1a, 0x0, 0x0, 0x0, ...)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/http/transport.go:898 +0x214
net/http.(*Transport).dialConn(0xa0e080, 0x837760, 0xc042052098, 0x0, 0xc04207c6c0, 0x5, 0xc042050c20, 0x1a, 0x0, 0x0, ...)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/http/transport.go:1143 +0x31e
net/http.(*Transport).getConn.func4(0xa0e080, 0x837760, 0xc042052098, 0xc042144390, 0xc0420441e0)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/http/transport.go:957 +0x7f
created by net/http.(*Transport).getConn
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/http/transport.go:956 +0x36a

goroutine 5 [select]:
net.(*Resolver).lookupIP(0xa12a70, 0x837720, 0xc04203e080, 0xc042050c20, 0x16, 0x0, 0xc042024a80, 0xc04203e040, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/lookup_windows.go:118 +0x17b
net.(*Resolver).(net.lookupIP)-fm(0x837720, 0xc04203e080, 0xc042050c20, 0x16, 0x429d40, 0x8, 0xc04203e040, 0x0, 0xc042163ea0)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/lookup.go:192 +0x5d
net.glob..func10(0x837720, 0xc04203e080, 0xc042036040, 0xc042050c20, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/hook.go:19 +0x59
net.(*Resolver).LookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/net/lookup.go:206 +0xdf
internal/singleflight.(*Group).doCall(0xa12a60, 0xc04216a050, 0xc042050c20, 0x16, 0xc042166090)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/internal/singleflight/singleflight.go:95 +0x35
created by internal/singleflight.(*Group).DoChan
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/internal/singleflight/singleflight.go:88 +0x2d7
rax     0x7fffca360b92
rbx     0x7fffca360b90
rcx     0x77
rdi     0xffffffffffbadd11
rsi     0x0
rbp     0x0
rsp     0x38ceae0
r8      0x97c
r9      0x97c
r10     0x97c
r11     0x97c
r12     0xc000007a
r13     0x0
r14     0x7fffca360b92
r15     0x7fffcd430000
rip     0x14f0000
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
```

I am able to switch to version that is already installed on system:

e.g.
```ps
> gvm --version
v0.2.2
> gvm list
1.14.3
> gvm --format=powershell 1.14.3
$env:GOROOT = "C:\Users\stefan\.gvm\versions\go1.14.3.windows.amd64"
$env:PATH = "C:\Users\stefan\.gvm\versions\go1.14.3.windows.amd64\bin;$env:PATH"
```

**Comment by stefanjarina** [comment]
Hi, nevermind, found it was doing AV "Webroot SecureAnywhere". Dunno what it was exactly doing, but I had to uninstall it completely (turning it on/off or tuning whitelists didn't help)
It was breaking also other apps written in go, including my own. Switched to different AV just because of that.
